Proper mapping language codes to ISO 639-3
openzim/phet pull request #201
Opened 2023-02-25 13:58 UTC by pavel-karatsiuba

With this PR the ZIM metadata option "Language" will not contain the "mul" value. Instead of the "mul" for multilanguage zim will be used list of languages with a comma separator.

2023-02-25 20:33 UTC, kelson42 requested changes
@pavel-karatsiuba What will happen if a new language comes and can not be converted?

2023-02-26 10:08 UTC, pavel-karatsiuba commented
> @pavel-karatsiuba What will happen if a new language comes and can not be converted?
@kelson42 
If the language will not be iso639-1 then the Language metadata will be empty. If the new language will be iso639-1 then it will be converted to iso639-3 and added to the Language metadata.

2023-02-26 10:25 UTC, kelson42 commented
> If the language will not be iso639-1 then the Language metadata will be empty.

This is against the spec. This should never happen. Scraper should properly die if this happens. Please check the spec to ensure you always have all important information and always think to all edge case scenarios. Otherwise we will end-up in an unoptimal long list of PRs.

2023-02-26 20:15 UTC, kelson42 approved these changes

2023-02-26 20:16 UTC, merged